name: grouped_list
description: A Flutter ListView where the list items can be grouped into sections.
version: 4.0.0
homepage: https://begnis.dev
repository: https://github.com/Dimibe/grouped_list


environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  pull_to_refresh: ^1.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0